### ISSUE TITLE
Pandas 0.22.0 causes error

### ISSUE THREAD

**Issue by avanderburg** [timothydmorton/VESPA#13]
Using Pandas 0.22.0 causes the following error. Downgrading to Pandas 0.20.1 fixes the problem.  

Traceback (most recent call last):
  File "/home/avanderb/anaconda4/bin/calcfpp", line 141, in <module>
    n=args.n)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/vespa/fpp.py", line 351, in from_ini
    savefile=popset_file, **kwargs)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/vespa/populations.py", line 2015, in __init__
    do_only=do_only)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/vespa/populations.py", line 2170, in generate
    hebpop = HEBPopulation.load_hdf(savefile, 'heb')
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/vespa/populations.py", line 943, in load_hdf
    new = StarPopulation.load_hdf(filename, path=path)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/vespa/stars/populations.py", line 1084, in load_hdf
    stars = pd.read_hdf(filename,path+'/stars', autoclose=True)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/pandas/io/pytables.py", line 349, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/pandas/io/pytables.py", line 467, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/avanderb/anaconda4/lib/python2.7/site-packages/pandas/io/pytables.py", line 605, in open
    raise e
ValueError: The file '/data/k2/misc/vespa/lp358-348ctest4/popset.h5' is already opened, but not in read-only mode (as requested).
Closing remaining open files:/data/k2/misc/vespa/lp358-348ctest4/popset.h5...done/data/k2/misc/vespa/lp358-348ctest4/popset.h5...done/data/k2/misc/vespa/lp358-348ctest4/popset.h5...done/data/k2/misc/vespa/lp358-348ctest4/popset.h5...done/data/k2/misc/vespa/lp358-348ctest4/popset.h5...done

**Comment by timothydmorton** [comment]
I'm still getting this, too, but it goes away if I just run `calcfpp` again.  So there's some bug in there, but I can't figure out where it is.  I can't track down where these files are being left open...

**Comment by timothydmorton** [comment]
Got it, finally-- it was hiding in isochrones: https://github.com/timothydmorton/isochrones/commit/ea324e1d590d8f675f570dfee500580212311a31
