### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by campante80** [timothydmorton/VESPA#15]
Hi Tim,

While trying to perform a bootstrapping I get the following error:

********************************************************************
FPP calculation failed for ..
Traceback (most recent call last):
  File "/Applications/anaconda/envs/python2/bin/calcfpp", line 154, in <module>
    f.bootstrap_FPP(args.bootstrap)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/vespa/fpp.py", line 861, in bootstrap_FPP
    new = FPPCalculation(self.trsig, self.popset.resample(), folder=self.folder)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/vespa/populations.py", line 2513, in resample
    new_poplist = [pop.resample() for pop in new.poplist]
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/vespa/populations.py", line 990, in resample
    new._make_kde()
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/vespa/populations.py", line 523, in _make_kde
    logdeps = logdeps[ok]
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/series.py", line 640, in __getitem__
    key = check_bool_indexer(self.index, key)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1936, in check_bool_indexer
    result = result.reindex(ax)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/series.py", line 2426, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/generic.py", line 2404, in reindex
    fill_value, copy).__finalize__(self)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/generic.py", line 2422, in _reindex_axes
    copy=copy, allow_dups=False)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/generic.py", line 2516, in _reindex_with_indexers
    copy=copy)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/Applications/anaconda/envs/python2/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2787, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
********************************************************************

The problem seems to be related to the self.distok property, which in turn may be due to the constraints not being correctly resampled prior to calling _make_kde() inside resample(). You even left a note related to this in the header of the latter function. Any thoughts?

Cheers,
Tiago

**Comment by timothydmorton** [comment]
Good question; I'm not currently testing the bootstrapping method in my tests; this is a good reminder.  I also don't think I've ever done the bootstrapping while applying observational constraints.  I will be able to investigate this maybe next week.  Can you post what your `fpp.ini` looks like? (you can fake the RA/Dec and name if you'd rather not broadcast what system you're working on; I know some people may be sensitive about that)

**Comment by timothydmorton** [comment]
So I just got a maximum recursion depth error when trying to run `calcfpp --bootstrap 3 kepler-22`.  Problem seems to be when trying to do `new = copy.deepcopy(self)` during the `resample` method.  But you seem to be able to call `resample` ok.  Are you running current versions of both isochrones and vespa?

**Comment by campante80** [comment]
Installed `vespa` with `pip` a couple of weeks ago. It came with `isochrones 0.9.1`, which I'm still currently using. I'm also using `pandas 0.20.1`.

The `ValueError` I reported happens as a result of executing `ok = second_ok & self.distok` inside `_make_kde()` and then using `ok` for indexing.

The call to `_make_kde()` is made from within `resample`, which appears to be running smoothly.

Played a bit with the way you resample stars inside `resample`. By simply omitting the `reset_index()` method, i.e., using `new.stars = new.stars.iloc[inds]` instead, I get the bootstrapping to work. Didn't see the need for a new sequential index, that being the rationale for doing this. Feel we're getting closer...

**Comment by timothydmorton** [comment]
I don't remember why I reset the index, but I'm sure there was a reason, so I don't want to throw that away.  However, I see that the line  `ok = second_ok & self.distok` actually results in a series of length *longer* than it's supposed to be----I'm doing the test with N=100, and dropping into `pdb` tells me that `len(ok)` is 139.  This gets fixed by using `ok = np.logical_and(second_ok, self.distok)`.  Not sure exactly what is happening there, but probably something unexpected happening with pandas indexing.  Probably time to go through the code and use that type of boolean array logic everywhere.

Also, btw, I do encourage you to update to the most recent versions of isochrones/vespa.  I'll be pushing a fix to this issue later today, but it will be on vespa's master branch, for which you will also need the latest isochrones.  Note too, that I am currently testing only in python 3, so there may be some unexpected py2 issues.

**Comment by timothydmorton** [comment]
Actually, everything comes back to the fact that the masks in the `Constraint` objects are assumed to be numpy arrays but actually series.  Forcing those to be arrays, everything should work OK.  Will double-check this in a bit.

**Comment by timothydmorton** [comment]
This is now fixed on master, and bootstrapping is working.

**Comment by campante80** [comment]
Brilliant. Can confirm it works. And yes, will be updating to the most recent versions of isochrones/vespa. Thanks.
