### ISSUE TITLE
Can't install latest (v.0.5)

### ISSUE THREAD

**Issue by elisabethadams** [timothydmorton/VESPA#17]
The latest isochrones (v 1.2) is fine, but vespa installation dies on a gcc error (here's the pip install error log, but the git cloning result was similar).

`    creating build/temp.macosx-10.6-x86_64-2.7/vespa
    gcc -fno-strict-aliasing -I//anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/lib/python2.7/site-packages/numpy/core/include -I//anaconda/include/python2.7 -c vespa/_transitutils.c -o build/temp.macosx-10.6-x86_64-2.7/vespa/_transitutils.o
    In file included from /opt/local/lib/gcc49/gcc/x86_64-apple-darwin16/4.9.4/include-fixed/syslimits.h:7:0,
                     from /opt/local/lib/gcc49/gcc/x86_64-apple-darwin16/4.9.4/include-fixed/limits.h:34,
                     from //anaconda/include/python2.7/Python.h:19,
                     from vespa/_transitutils.c:23:
    /opt/local/lib/gcc49/gcc/x86_64-apple-darwin16/4.9.4/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "//anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/kv/p51v_tbj5gjdd9q0jk4k2_5r0000gn/T/pip-install-dMif00/vespa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kv/p51v_tbj5gjdd9q0jk4k2_5r0000gn/T/pip-record-V1nbOu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/kv/p51v_tbj5gjdd9q0jk4k2_5r0000gn/T/pip-install-dMif00/vespa/`

**Comment by jxcbecker** [comment]
Hi Elisabeth - I dealt with this problem as well (I think it's the same one you have). It's actually not a VESPA issue, it's a compiler issue that's been popping up for me with the new version of MacOS (which uses clang as the c compiler?). I think for me it was because different packages (via conda, pip) I had installed with different compilers. 

For me, creating a new conda virtual environment and installing everything (Python 3) fresh using the anaconda2/bin/gcc worked. 

Do you have the Xcode developer tools? If not, you could try getting them, that would be a much easier fix and would cause the same error.

**Comment by jpdeleon** [comment]
After installing vespa, I run `calcfpp` as follows

```shell
$ calcfpp
WARNING:root:PyMultiNest not imported.  MultiNest fits will not work.
WARNING:root:sklearn not available
WARNING:root:progressbar not imported
WARNING:root:Cadence not provided in fpp.ini; defaulting to Kepler cadence.
Cadence not provided in fpp.ini; defaulting to Kepler cadence.
WARNING:root:If this is not a Kepler target, please set cadence (in days).
If this is not a Kepler target, please set cadence (in days).
INFO:root:Fitting transitsignal with MCMC...
Fitting transitsignal with MCMC...
INFO:root:Fitting data to trapezoid shape with MCMC for 211314705....
Fitting data to trapezoid shape with MCMC for 211314705....
INFO:root:Generating ['beb', 'heb', 'eb', 'beb_Px2', 'heb_Px2', 'eb_Px2', 'pl'] models for PopulationSet...
Generating ['beb', 'heb', 'eb', 'beb_Px2', 'heb_Px2', 'eb_Px2', 'pl'] models for PopulationSet...
INFO:root:15471 eclipsing HEB systems generated (target 20000)
15471 eclipsing HEB systems generated (target 20000)
INFO:root:20982 eclipsing HEB systems generated (target 20000)
20982 eclipsing HEB systems generated (target 20000)
INFO:root:Fitting trapezoid models for HEBs...
Fitting trapezoid models for HEBs...
INFO:root:Done.
Done.
INFO:root:17277 eclipsing HEB systems generated (target 20000)
17277 eclipsing HEB systems generated (target 20000)
INFO:root:20741 eclipsing HEB systems generated (target 20000)
20741 eclipsing HEB systems generated (target 20000)
INFO:root:Fitting trapezoid models for HEBs (Double Period)...
Fitting trapezoid models for HEBs (Double Period)...
ERROR:root:No eclipse registered for star 12220
No eclipse registered for star 12220
INFO:root:Done.
Done.
INFO:root:14970 Eclipsing EB systems generated (target 20000)
14970 Eclipsing EB systems generated (target 20000)
INFO:root:20940 Eclipsing EB systems generated (target 20000)
20940 Eclipsing EB systems generated (target 20000)
INFO:root:Fitting trapezoid models for EBs...
Fitting trapezoid models for EBs...
INFO:root:Done.
Done.
INFO:root:16754 Eclipsing EB systems generated (target 20000)
16754 Eclipsing EB systems generated (target 20000)
INFO:root:20653 Eclipsing EB systems generated (target 20000)
20653 Eclipsing EB systems generated (target 20000)
INFO:root:Fitting trapezoid models for EBs (Double Period)...
Fitting trapezoid models for EBs (Double Period)...
ERROR:root:No eclipse registered for star 1839
No eclipse registered for star 1839
ERROR:root:No eclipse registered for star 2875
No eclipse registered for star 2875
INFO:root:Done.
Done.
INFO:root:Getting TRILEGAL simulation at 129.129927, 10.147280...
Getting TRILEGAL simulation at 129.129927, 10.147280...
/bin/sh: 1: curl: not found
ERROR:root:Error generating BEB population.
Error generating BEB population.
ERROR:root:FPP calculation failed for ..
Traceback (most recent call last):
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/EGG-INFO/scripts/calcfpp", line 151, in <module>
    n=args.n)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/fpp.py", line 288, in from_ini
    savefile=popset_file, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 2036, in __init__
    do_only=do_only)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 2151, in generate
    mags=mags, MAfn=MAfn, n=n, **beb_kws)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 1753, in __init__
    maxrad=maxrad, f_binary=f_binary, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 1782, in generate
    maxrad=maxrad, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/populations.py", line 2193, in __init__
    get_trilegal(basefilename,ra,dec,**kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/trilegal.py", line 92, in get_trilegal
    AV = get_AV_infinity(l,b,frame='galactic')
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/extinction.py", line 45, in get_AV_infinity
    with open(tmpfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nedsearch215.647582078959927.910368050815226.html'
FPP calculation failed for ..
Traceback (most recent call last):
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/EGG-INFO/scripts/calcfpp", line 151, in <module>
    n=args.n)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/fpp.py", line 288, in from_ini
    savefile=popset_file, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 2036, in __init__
    do_only=do_only)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 2151, in generate
    mags=mags, MAfn=MAfn, n=n, **beb_kws)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 1753, in __init__
    maxrad=maxrad, f_binary=f_binary, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/populations.py", line 1782, in generate
    maxrad=maxrad, **kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/populations.py", line 2193, in __init__
    get_trilegal(basefilename,ra,dec,**kwargs)
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/trilegal.py", line 92, in get_trilegal
    AV = get_AV_infinity(l,b,frame='galactic')
  File "/home/prometheus/miniconda3/envs/vespa/lib/python3.5/site-packages/VESPA-0.5.1-py3.5-linux-x86_64.egg/vespa/stars/extinction.py", line 45, in get_AV_infinity
    with open(tmpfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nedsearch215.647582078959927.910368050815226.html'
```

```shell
$ conda list
# packages in environment at /home/prometheus/miniconda3/envs/vespa:
#
asn1crypto                0.24.0                    <pip>
astropy                   2.0.1               np113py35_0  
astroquery                0.3.9.dev0                <pip>
batman-package            2.4.6                     <pip>
beautifulsoup4            4.7.1                     <pip>
blas                      1.0                         mkl  
certifi                   2016.2.28                py35_0  
certifi                   2019.3.9                  <pip>
cffi                      1.12.2                    <pip>
chardet                   3.0.4                     <pip>
cryptography              2.6.1                     <pip>
cycler                    0.10.0                   py35_0  
cython                    0.26                     py35_0  
dbus                      1.10.20                       0  
emcee                     2.2.1                     <pip>
entrypoints               0.3                       <pip>
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
html5lib                  1.0.1                     <pip>
icu                       54.1                          0  
idna                      2.8                       <pip>
isochrones                1.2.1                     <pip>
jeepney                   0.4                       <pip>
jpeg                      9b                            0  
keyring                   19.0.1                    <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libiconv                  1.14                          0  
libpng                    1.6.30                        1  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
llvmlite                  0.28.0                    <pip>
matplotlib                2.0.2               np113py35_0  
mkl                       2017.0.3                      0  
mock                      2.0.0                     <pip>
numba                     0.43.1                    <pip>
numexpr                   2.6.9                     <pip>
numpy                     1.13.1                   py35_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py35_0  
pandas                    0.23.4                    <pip>
pandas                    0.24.2                    <pip>
pbr                       5.1.3                     <pip>
pcre                      8.39                          1  
pip                       19.0.3                    <pip>
pip                       9.0.1                    py35_1  
plotutils                 0.3.2                     <pip>
py                        1.4.34                   py35_0  
pycparser                 2.19                      <pip>
pyparsing                 2.2.0                    py35_0  
pyqt                      5.6.0                    py35_2  
pytest                    3.2.1                    py35_0  
python                    3.5.4                         0  
python-dateutil           2.6.1                    py35_0  
pytz                      2017.2                   py35_0  
qt                        5.6.2                         5  
readline                  6.2                           2  
requests                  2.21.0                    <pip>
scipy                     1.2.0rc2                  <pip>
SecretStorage             3.1.1                     <pip>
setuptools                36.4.0                   py35_1  
simpledist                0.1.13                    <pip>
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
soupsieve                 1.9                       <pip>
sqlite                    3.13.0                        0  
tables                    3.5.1                     <pip>
tk                        8.5.18                        0  
urllib3                   1.24.1                    <pip>
VESPA                     0.5.1                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py35_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0
```
