### ISSUE TITLE
Cannot load previously created popset files

### ISSUE THREAD

**Issue by jxcbecker** [timothydmorton/VESPA#18]
When trying to load a previously created popset file using Vespa version 0.5, it cannot open the file, and errors as follows:

> from vespa import PopulationSet
> popset = PopulationSet.load_hdf('/Users/jcbecker/Documents/GitHub/vespa-tutorial/Notebooks/TestCase3/popset.h5')

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/vespa/populations.py", line 2227, in load_hdf
    poplist.append(t().load_hdf(filename, path='{}/{}'.format(path,m)))
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/vespa/populations.py", line 941, in load_hdf
    new = StarPopulation.load_hdf(filename, path=path)
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/vespa/stars/populations.py", line 1081, in load_hdf
    stars = pd.read_hdf(filename,path+'/stars')
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/pandas/io/pytables.py", line 373, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/pandas/io/pytables.py", line 491, in __init__
    self.open(mode=mode, **kwargs)
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/pandas/io/pytables.py", line 629, in open
    raise e
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/pandas/io/pytables.py", line 604, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/Users/jcbecker/anaconda2/envs/vespa/lib/python3.6/site-packages/tables/file.py", line 306, in open_file
    "not in read-only mode (as requested)." % filename)
ValueError: The file '/Users/jcbecker/Documents/GitHub/vespa-tutorial/Notebooks/TestCase3/popset.h5' is already opened, but not in read-only mode (as requested).```

**Comment by timothydmorton** [comment]
Fix just pushed to master.  let me know if this works for you.

**Comment by jxcbecker** [comment]
It works perfectly now! Thanks!
