### ISSUE TITLE
All simulated systems within Roche lobe

### ISSUE THREAD

**Issue by elisabethadams** [timothydmorton/VESPA#27]
Probably needs some more robust error checking?

```
2019-02-15 17:42:15,270: Error generating HEB population.
2019-02-15 17:42:15,270: FPP calculation failed for ..
Traceback (most recent call last):
  File "//anaconda/envs/vespa3/bin/calcfpp", line 151, in <module>
    n=args.n)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/fpp.py", line 269, in from_ini
    savefile=popset_file, **kwargs)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/populations.py", line 2014, in __init__
    do_only=do_only)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/populations.py", line 2058, in generate
    MAfn=MAfn, n=n, **heb_kws)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/populations.py", line 1515, in __init__
    **kwargs)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/populations.py", line 1576, in generate
    MAfn=MAfn)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/populations.py", line 2696, in calculate_eclipses
    mininc = minimum_inclination(Ps, M1s, M2s, R1s, R2s)
  File "//anaconda/envs/vespa3/lib/python3.6/site-packages/vespa/transit_basic.py", line 324, in minimum_inclination
    raise AllWithinRocheError('All simulated systems within Roche lobe')
vespa.transit_basic.AllWithinRocheError: All simulated systems within Roche lobe
```

**Comment by elisabethadams** [comment]
Here are a few more errors that have been cropping up, for anyone who is struggling with the same; I haven't figured them all out so let me know if you have suggestions. (I'm running a variety of targets with different constraints.)

1. "x must be strictly increasing" -- [Solved] Go check the AO constraint file and remove lines that aren’t strictly greater than the one before 

2. KeyError: ‘R_mag_A'  -- [SOLVED-ish] The list of allowed constraints in vespa/stars/populations.py is 
['g','r','i','z','J','H','K','Kepler'] and changing a constraint file name from "Telescope_R.cc" to "Telescope_r.cc" will make vespa run.  (However, sometimes it still ran with R anyways...?)

3. "All simulated systems within Roche lobe" -- This only shows up in planets with extremely short periods (P<=0.17 d in my sample); not sure what it means though.

4.  ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)  -- ??

5. TransitSignal trapezoid fit not converged  -- ??

**Comment by timothydmorton** [comment]
3.  This error happens when the radii of all the simulated host stars is comparable to the size of the orbit of the planet candidate.  

4.  Not about this one.

5.  This means that the trapezoid MCMC fit did not converge.  There might be several reasons for this; perhaps the automated parameter initialization fails, or perhaps too much of out-of-transit signal is included for the simple flat + trapezoid model.

**Comment by elisabethadams** [comment]
Some more experimenting:

4. [SOLVED] by deleting the trsig.pkl file and trying again

5. [SOLVED] by deleting the trsig.pkl file and trying again, except for one case that might be more pathological (will try your suggestions).

**Comment by priyashmistry** [comment]
3. For my selected TESS candidates,
    Roche lobe error was occurred for the targets having g, r, i, z band magnitudes in star.ini file. removing them and re-running 
    starfit --all and calcfpp worked fine.
