### ISSUE TITLE
calcfpp gives RuntimeError: Cannot load StarModels. please run 'starfit --all'

### ISSUE THREAD

**Issue by eesopee** [timothydmorton/VESPA#32]
Hi Tim, I'm having this issue with VESPA while trying to run the Kepler-22 example. If I run calcfpp I get the following error:

```
eesopee@eesopee-PC:~/Desktop/test$ calcfpp
/home/eesopee/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py:2286: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)
WARNING:root:sklearn not available
WARNING:root:Cadence not provided in fpp.ini; defaulting to Kepler cadence.
Cadence not provided in fpp.ini; defaulting to Kepler cadence.
WARNING:root:If this is not a Kepler target, please set cadence (in days).
If this is not a Kepler target, please set cadence (in days).
'No object named /obs/df in the file'
ERROR:root:FPP calculation failed for ..
Traceback (most recent call last):
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/vespa/fpp.py", line 229, in from_ini
    single_starmodel = StarModel.load_hdf(single_starmodel_file)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/isochrones/starmodel.py", line 1151, in load_hdf
    obs = ObservationTree.load_hdf(filename, path+'/obs', ic=ic)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/isochrones/observation.py", line 869, in load_hdf
    samples = store[path+'/df']
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 504, in __getitem__
    return self.get(key)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 694, in get
    raise KeyError('No object named {key} in the file'.format(key=key))
KeyError: 'No object named /obs/df in the file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/calcfpp", line 151, in <module>
    n=args.n)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/vespa/fpp.py", line 235, in from_ini
    'Please run `starfit --all {}`.'.format(folder))
RuntimeError: Cannot load StarModels.  Please run `starfit --all .`.
FPP calculation failed for ..
Traceback (most recent call last):
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/vespa/fpp.py", line 229, in from_ini
    single_starmodel = StarModel.load_hdf(single_starmodel_file)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/isochrones/starmodel.py", line 1151, in load_hdf
    obs = ObservationTree.load_hdf(filename, path+'/obs', ic=ic)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/isochrones/observation.py", line 869, in load_hdf
    samples = store[path+'/df']
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 504, in __getitem__
    return self.get(key)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 694, in get
    raise KeyError('No object named {key} in the file'.format(key=key))
KeyError: 'No object named /obs/df in the file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/calcfpp", line 151, in <module>
    n=args.n)
  File "/home/eesopee/anaconda3/lib/python3.7/site-packages/VESPA-0.5.1-py3.7-linux-x86_64.egg/vespa/fpp.py", line 235, in from_ini
    'Please run `starfit --all {}`.'.format(folder))
RuntimeError: Cannot load StarModels.  Please run `starfit --all .`.

```
It says to run starfit --all but I've already done that, and the calculation looked succesful.

Any ideas about how to fix this? Thanks in advance!

**Comment by StjaniV** [comment]
I have the exact same problem! I'm working on a windows subsystem btw.
